// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvH3rJvOqY5KQGdL8N8XjQvKZHgYmE123',
    appId: '1:847892341234:web:winetory123456789abc',
    messagingSenderId: '847892341234',
    projectId: 'wine-tory-management-system',
    authDomain: 'wine-tory-management-system.firebaseapp.com',
    storageBucket: 'wine-tory-management-system.appspot.com',
    measurementId: 'G-WINETORY123',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvH3rJvOqY5KQGdL8N8XjQvKZHgYmE123',
    appId: '1:847892341234:android:winetory123456789def',
    messagingSenderId: '847892341234',
    projectId: 'wine-tory-management-system',
    storageBucket: 'wine-tory-management-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvH3rJvOqY5KQGdL8N8XjQvKZHgYmE123',
    appId: '1:847892341234:ios:winetory123456789ghi',
    messagingSenderId: '847892341234',
    projectId: 'wine-tory-management-system',
    storageBucket: 'wine-tory-management-system.appspot.com',
    iosBundleId: 'com.winetory.management',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvH3rJvOqY5KQGdL8N8XjQvKZHgYmE123',
    appId: '1:847892341234:ios:winetory123456789ghi',
    messagingSenderId: '847892341234',
    projectId: 'wine-tory-management-system',
    storageBucket: 'wine-tory-management-system.appspot.com',
    iosBundleId: 'com.winetory.management',
  );
}